/* config.h -- generated by the CMake build of libiscsi.
 *
 * This is the CMake equivalent of the config.h that autoheader generates
 * from config.h.in. Keep the two in sync when adding new feature tests.
 */
#ifndef LIBISCSI_CMAKE_CONFIG_H
#define LIBISCSI_CMAKE_CONFIG_H

/* Header files */
#cmakedefine HAVE_ARPA_INET_H 1
#cmakedefine HAVE_DISPATCH_DISPATCH_H 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_NETINET_IN_H 1
#cmakedefine HAVE_NETINET_TCP_H 1
#cmakedefine HAVE_POLL_H 1
#cmakedefine HAVE_STDATOMIC_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_SELECT_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_UIO_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_WINSOCK_H 1
#cmakedefine HAVE_WINSOCK2_H 1
#cmakedefine HAVE_WS2TCPIP_H 1
#cmakedefine STDC_HEADERS 1

/* Libraries */
#cmakedefine HAVE_LIBGCRYPT 1
#cmakedefine HAVE_LIBGNUTLS 1
#cmakedefine HAVE_LIBNSL 1
#cmakedefine HAVE_LIBPTHREAD 1
#cmakedefine HAVE_LIBSOCKET 1
#cmakedefine HAVE_LIBWS2_32 1

/* Functions */
#cmakedefine HAVE_CLOCK_GETTIME 1
#cmakedefine HAVE_PTHREAD_THREADID_NP 1
#cmakedefine HAVE_TZSET 1

/* Features */
#cmakedefine HAVE_CU_SUITEINFO_PSETUPFUNC 1
#cmakedefine HAVE_LINUX_ISER 1
#cmakedefine HAVE_MULTITHREADING 1
#cmakedefine HAVE_PTHREAD 1
#cmakedefine HAVE_RDMA_ACK_TIMEOUT 1
#cmakedefine HAVE_SG_IO 1
#cmakedefine HAVE_SOCKADDR_IN6 1
#cmakedefine HAVE_SOCK_SIN_LEN 1
#cmakedefine HAVE_TIMEZONE_TZ_DSTTIME 1
#cmakedefine NEED_SYS_FILIO_H 1

/* Type of the fifth argument of select() */
#cmakedefine SELECT_TIMEVAL_TYPE @SELECT_TIMEVAL_TYPE@

/* Package information */
#define PACKAGE "@PROJECT_NAME@"
#define PACKAGE_NAME "@PROJECT_NAME@"
#define PACKAGE_TARNAME "@PROJECT_NAME@"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "@PROJECT_NAME@ @PROJECT_VERSION@"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define VERSION "@PROJECT_VERSION@"

#endif /* LIBISCSI_CMAKE_CONFIG_H */
